apiVersion: v2
name: nexus
version: 3.87.1
appVersion: "3.87.1"
kubeVersion: ">= 1.13.0"
description: Sonatype Nexus Repository Manager Helm Chart
type: application
home: https://github.com/Scalified/helm-nexus
icon: https://scalified.github.io/helm-nexus/icon.png
maintainers:
  - name: Vladyslav Baidak
    email: vld.x@hotmail.com
    url: https://scalified.com
keywords:
  - sonatype
  - nexus
  - artifacts
  - repository
  - dependency
  - management
annotations:
  artifacthub.io/category: integration-delivery
  artifacthub.io/signKey: |
    fingerprint: 687D9BE990493C58C0CFBEB65A065879383D7E21
    url: https://keybase.io/scalified/pgp_keys.asc
