name: Sync Helm chart version

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

    
jobs:
  sync-chart-version:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Sync chart version
        uses: Scalified/helm-chart-version-sync-action@v1
        with:
          dockerhub-namespace: sonatype
          dockerhub-repository: nexus3
          chart-file-path: charts/nexus/Chart.yaml
          docker-image-tag-pattern: '^v?[0-9]+\.[0-9]+\.[0-9]+$'
